### ISSUE TITLE
bug: When using the baichuan2-13b-chat-q4-k-m model, the output is completely nonsensical.

### ISSUE THREAD

**Issue by duliangang** [LlamaEdge/LlamaEdge#102]
### Summary

![image](https://github.com/second-state/LlamaEdge/assets/1728593/e7bf114f-e278-473b-94e9-b49ea12ced73)
![image](https://github.com/second-state/LlamaEdge/assets/1728593/c6261d80-3d68-453d-bf30-5189b44344e4)

### Reproduction steps

![image](https://github.com/second-state/LlamaEdge/assets/1728593/7d953a28-e9ec-4834-8908-4db428f68bb1)

### Screenshots

![DESCRIPTION](LINK.png)

### Model Information

Baichuan2-13B-Chat-Q4_K_M.gguf

### Operating system information

ubuntu 22

### ARCH

amd64

### CPU Information

amd 5800x

### Memory Size

64G

### GPU Information

3090

### VRAM Size

24G

**Comment by duliangang** [comment]
chat model 
![image](https://github.com/second-state/LlamaEdge/assets/1728593/552952ee-faa6-457e-a05c-c0bcff8e3fa1)

**Comment by alabulei1** [comment]
@apepkuss  Please take a look. Thanks.

**Comment by apepkuss** [comment]
@duliangang Thanks for your report. We have already reproduced the issue. According to our judgment, it could be the quantized models. We updated the models in [second-state/Baichuan2-13B-Chat-GGUF](https://huggingface.co/second-state/Baichuan2-13B-Chat-GGUF) with `llama.cpp b1953` recently. We'll check the issue further and feedback to you asap. Thanks a lot!

**Comment by apepkuss** [comment]
@duliangang We updated the gguf models in [second-state/Baichuan2-13B-Chat-GGUF](https://huggingface.co/second-state/Baichuan2-13B-Chat-GGUF). Please download the model you need and try it again. Thanks!

**Comment by apepkuss** [comment]
@duliangang Is this issue still there on your side? Thanks!
