### ISSUE TITLE
Migration: Update the urls to the new repo

### ISSUE THREAD

**Issue by apepkuss** [LlamaEdge/LlamaEdge#116]
### Summary

The following resources should be checked and updated:

- [x] models in [huggingface/second-state](https://huggingface.co/second-state)
- [ ] [LangChain LlamaEdge Integration Tutorial](https://python.langchain.com/docs/integrations/chat/llama_edge)
- [x] run-llm.sh
- [x] [flows.network download-counter](https://github.com/flows-network/downloads-counter/blob/main/URLS.json), see https://github.com/flows-network/downloads-counter/pull/1
- [x] Second State Articles
- [ ] Michael Yuan's medium article
- [x] WasmEdge Docs see https://github.com/WasmEdge/docs/pull/215
- [x] Readme in LlamaEdge/LlamaEdge repo, see #118

**Comment by MileyFu** [comment]
- [ ] Youtube videos descriptions
- [ ] Zhihhu
