### ISSUE TITLE
bug: failed to allocate buffer

### ISSUE THREAD

**Issue by realcarlos** [LlamaEdge/LlamaEdge#130]
### Summary

********************* [LOG: MODEL INFO (Load Model & Init Execution Context)] *********************[2024-03-07 20:57:31.423] [error] instantiation failed: module name conflict, Code: 0x60
[2024-03-07 20:57:31.424] [error]     At AST node: module
[INFO] Socket address: 0.0.0.0:8080
[INFO] Model name: Yi-34Bx2-MoE-60B
[INFO] Model alias: default
[INFO] Prompt context size: 512
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 1
[INFO] Top-p sampling (1.0 = disabled): 1
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Presence penalty (0.0 = disabled): 0
[INFO] Frequency penalty (0.0 = disabled): 0
[INFO] Reverse prompt: <|im_end|>
[INFO] Prompt template: ChatML
[INFO] Log prompts: true
[INFO] Log statistics: true
[INFO] Log all information: false
[INFO] Starting server ...

### Reproduction steps

bash run-llm.sh --model yi-34bx2-moe-60b

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

llama_model_load: error loading model: failed to allocate buffer
llama_load_model_from_file: failed to load model
[2024-03-07 20:57:31.574] [error] [WASI-NN] GGML backend: Error: unable to init model.
Error: Operation("Failed to initialize the core context. Backend Error: WASI-NN Backend Error: Caller module passed an invalid argument")

### Model Information

Yi-34Bx2-MoE-60B-Q5_K_M.gguf"

### Operating system information

Mac OS 14.2

### ARCH

arm46

### CPU Information

AppleM2 

### Memory Size

192GB

### GPU Information

AppleM2

### VRAM Size

192

**Comment by hydai** [comment]
Hi @realcarlos 
Could you check the model is downloaded correctly via the model size and checksum?
Is your VRAM available to load the entire model at that time?

**Comment by realcarlos** [comment]
> Hi @realcarlos Could you check the model is downloaded correctly via the model size and checksum? Is your VRAM available to load the entire model at that time?

thanks , there is 192 GB memory in MAC STUDIO , I will check it later

**Comment by hydai** [comment]
Hi @realcarlos 
Any update?
