### ISSUE TITLE
bug: Installation failed 

### ISSUE THREAD

**Issue by longzhi** [LlamaEdge/LlamaEdge#133]
### Summary

excute following command to install LlamaEdge:
bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh')
And then, something wrong throwed. Seems the installation script doesn't support Python 3.12.

[+] Installing WasmEdge with wasi-nn_ggml plugin ...

Using Python: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
<stdin>:250: SyntaxWarning: invalid escape sequence '\d'
<stdin>:1365: SyntaxWarning: invalid escape sequence '\+'
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1319, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1365, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1074, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1018, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1460, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1046, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1317, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

### Reproduction steps

execute command:
bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh')

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

<img width="1306" alt="image" src="https://github.com/LlamaEdge/LlamaEdge/assets/60097/8aeb93e4-1bdc-4ef8-84f4-bcf3ae3ac6fe">

### Model Information

llama2

### Operating system information

MacBook Pro Sonoma V14.4 (23E214)

### ARCH

arm64

### CPU Information

Apple M3 Pro

### Memory Size

18GB

### GPU Information

Apple M3 Pro

### VRAM Size

unknown

**Comment by hydai** [comment]
Please run `brew update & upgrade` to bump the python certifi

```console
==> Migrating formula python-certifi to certifi
==> Unlinking python-certifi
==> Moving python-certifi versions to /opt/homebrew/Cellar/certifi
==> Relinking certifi
```

If you are using another way to handle the Python runtime, please refer to:
https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore

**Comment by juntao** [comment]
This fails with the default Python install on macOS?

If so, we cannot ask the user to manually update anything. Is there a way to fix this on our end? Eg if this is a https very fail, perhaps we can use a different server for the assets?

**Comment by longzhi** [comment]
Yes, the script uses the default Python on my macOS.

**Comment by hydai** [comment]
> This fails with the default Python install on macOS?
> 
> If so, we cannot ask the user to manually update anything. Is there a way to fix this on our end? Eg if this is a https very fail, perhaps we can use a different server for the assets?

After checking the StackOverflow, I noticed that it seems like a very common issue after upgrading the macOS. The default shipped python should also be updated via Xcode's command line tools:
1. https://stackoverflow.com/questions/57630314/ssl-certificate-verify-failed-error-with-python3-on-macos-10-15/68247505#68247505
2. https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by apepkuss** [comment]
Closed. Please re-open it if any further question. Thanks!
