### ISSUE TITLE
Feature Request: add Number of Threads for better performance

### ISSUE THREAD

**Issue by njalan** [LlamaEdge/LlamaEdge#136]
### Summary

Is it to add add Number of Threads as the same parameter in llama.cpp

**Comment by zen1001** [comment]
[WASI-NN] ggml backend:
Bump llama.cpp to b2963.
Support llama.cpp options:
   threads: the thread number for inference.

Could you please add threads options to llama-core

**Comment by apepkuss** [comment]
@hydai Is it possible to support the `threads` option of llama.cpp? Thanks!

**Comment by hydai** [comment]
Hi @apepkuss 
We already supported it in WasmEdge for a while. So you should decide if Llamaedge wants to enable it or not.

Ref: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/ggml.cpp#L252-L259

**Comment by apepkuss** [comment]
@zen1001 We'll provide `--threads` CLI option for `llama-api-server` in the next release. You'll get it in days. Thanks!

**Comment by apepkuss** [comment]
@zen1001 We released llama-api-server [v.0.14.0](https://github.com/LlamaEdge/LlamaEdge/releases/tag/0.14.0), which provides `--threads` CLI option. Please try it on your side. Thanks a lot!
