### ISSUE TITLE
Output of llama-chat.wasm and llama-api-server.wasm is different

### ISSUE THREAD

**Issue by njalan** [LlamaEdge/LlamaEdge#138]
### Summary

Below is my command to start the service:

wasmedge --dir .:. --nn-preload default:GGML:CPU:qwen1_5-7b-chat-q5_k_m.gguf **llama-api-server.wasm** -p chatml -r '<|im_end|>' --log-prompts

wasmedge --dir .:. --nn-preload default:GGML:CPU:qwen1_5-7b-chat-q5_k_m.gguf **llama-chat.wasm** -c 2048 -n 512 -g 0  -p chatml

Here is the question:
 curl -X POST http://xxx:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"user", "content": "上海有什么好玩的"}], "model":"Qwen1.5-7B"}'

**Comment by juntao** [comment]
The system prompts are different for the two apps. You should `--log-prompts` to see the prompt that was actually sent to the LLM.

**Comment by njalan** [comment]
@juntao So how to add the prompt for  llama-api-server.wasm? I didn't find any parameter related it

**Comment by juntao** [comment]
It takes OpenAI style web API requests. 

Use the OpenAI JSON format to add a system  prompt to your API requests. Example

```

curl -X POST http://localhost:8080/v1/chat/completions \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"messages":[{"role":"system", "content": "You are a helpful assistant."}, {"role":"user", "content": "Where is Paris?"}], "model":"Llama-2-7b-chat-hf-Q5_K_M"}'
```

**Comment by njalan** [comment]
@juntao  I got the reason and I found that the completion_tokens for API is always 103. Is there any way to change this limitation?

**Comment by juntao** [comment]
I do not think there is an inherent constraint on completion tokens. Can you give a couple of examples to show that they are all 103?

**Comment by njalan** [comment]
@juntao  you can see all the completion_tokens is 103. Question can be "南京有什么好玩的" or "上海有什么好玩的"
<img width="433" alt="image" src="https://github.com/LlamaEdge/LlamaEdge/assets/8622340/adb6296d-f55f-40fd-be59-c51daa17b7c0">

**Comment by njalan** [comment]
@juntao  curl -X POST http://xxxx:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "南京有什么好玩的"}], "model":"default"}'

**Comment by juntao** [comment]
Here are my results. They are not "103 tokens".

```
curl -X POST http://localhost:8080/v1/chat/completions -H 'accept:application/json' -H 'Content-Type: application/json' -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "南京有什么好玩的"}], "model":"Llama-2-7b-chat-hf-Q5_K_M"}'

{"id":"7c072776-bf87-467f-b130-6b8d7ffa387f","object":"chat.completion","created":1711785476,"model":"Llama-2-7b-chat-hf-Q5_K_M","choices":[{"index":0,"message":{"role":"assistant","content":"Nanjing has many fun things to do! Here are a few recommendations:\n\n1. Visit the Purple Mountain (紫金山) - a popular hiking destination with beautiful scenery and historic sites.\n2. Explore the Nanjing City Wall (南京城墙) - a well-preserved ancient wall that offers stunning views of the city.\n3. Visit the Ming Xiaoling Mausoleum (明孝陵) - the tomb of the Ming dynasty's first emperor, Zhu Yuanzhang.\n4. Take a boat ride on the Yangtze River (长江) - a great way to see the city from a different perspective.\n5. Visit the Nanjing Museum (南京博物馆) - a museum showcasing the history and culture of Nanjing.\n6. Enjoy the local cuisine - Nanjing is known for its delicious food, including salted duck (盐鸭), salt-baked fish (盐焗鱼), and more."},"finish_reason":"stop"}],"usage":{"prompt_tokens":41,"completion_tokens":251,"total_tokens":292}}
```

and

```
curl -X POST http://localhost:8080/v1/chat/completions -H 'accept:application/json' -H 'Content-Type: application/json' -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "上海有什么好玩的"}], "model":"Llama-2-7b-chat-hf-Q5_K_M"}'

{"id":"2b64c329-ea86-429c-850f-3802b5251f39","object":"chat.completion","created":1711785533,"model":"Llama-2-7b-chat-hf-Q5_K_M","choices":[{"index":0,"message":{"role":"assistant","content":"Shanghai has many fun things to do! Here are a few recommendations:\n\n1. The Bund: A scenic waterfront area with stunning views of the city skyline and historic buildings.\n2. Shanghai Tower: The tallest building in China, offering panoramic views from its observation deck.\n3. Yu Garden: A traditional Chinese garden with beautiful architecture, tranquil ponds, and bonsai trees.\n4. Shanghai Museum: A world-class museum showcasing Chinese art and artifacts, including ancient bronzes, ceramics, and calligraphy.\n5. French Concession: A charming neighborhood with tree-lined streets, boutique shops, and trendy cafes.\n6. Shanghai Disneyland: A theme park with thrilling rides, shows, and attractions based on popular Disney characters.\n7. Xintiandi: A vibrant nightlife district with bars, clubs, and restaurants.\n8. Shanghai Aquarium: Home to over 10,000 marine animals, including sharks, penguins, and sea otters.\n9. Longhua Temple: A historic Buddhist temple with beautiful architecture and peaceful gardens.\n10. Zhangjiajie National Forest Park: A UNESCO World Heritage Site known for its towering sandstone pillars and stunning scenery."},"finish_reason":"stop"}],"usage":{"prompt_tokens":41,"completion_tokens":307,"total_tokens":348}}
```

**Comment by njalan** [comment]
@juntao 
Here is my testing:
  curl -X POST http://localhost:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "南京有什么好玩的"}]}'
{"id":"chatcmpl-d9c21b6a-a944-48fe-91f3-bfbd59d496b4","object":"chat.completion","created":1711812460,"model":"","choices":[{"index":0,"message":{"role":"assistant","content":"南京，作为中国历史文化名城和江苏省省会，拥有丰富的旅游资源。以下是一些推荐的游玩项目：\n\n1. **中山陵**：纪念孙中山先生的陵墓，风景优美，可了解其革命精神。\n2. **夫子庙秦淮河风光带**：古色古香的街巷，夜晚的秦淮灯会尤其有名。\n3. **南京博物院**：中国三大博物馆之一，藏品丰富，有深厚的历史底蕴。\n4. **"},"finish_reason":"stop"}],"usage":{"prompt_tokens":24,"completion_tokens":**103**,"total_tokens":127}}


  curl -X POST http://localhost:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "上海有什么好玩的"}]}'
{"id":"chatcmpl-792d3425-f1aa-482b-a5f2-bf91b62d034c","object":"chat.completion","created":1711812579,"model":"","choices":[{"index":0,"message":{"role":"assistant","content":"上海，作为中国最大的城市之一，拥有丰富的旅游资源和活动。以下是一些推荐的游玩项目：\n\n1. 外滩：欣赏黄浦江两岸的历史建筑群，包括东方明珠、金茂大厦等现代化地标。\n2. 陆家嘴：感受金融中心的繁华，可以参观上海环球金融中心、上海中心大厦等高楼，还有南京路步行街购物。\n3. 豫园：古典园林艺术的代表，有精致的江南水乡风格。\n4"},"finish_reason":"stop"}],"usage":{"prompt_tokens":24,"completion_tokens":**103**,"total_tokens":127}}


 curl -X POST http://localhost:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "生成三分钟小朋友的自我介绍"}]}'
{"id":"chatcmpl-f05b3543-e405-4908-9d5d-78ae668acb5b","object":"chat.completion","created":1711812835,"model":"","choices":[{"index":0,"message":{"role":"assistant","content":"当然可以，以下是一个简洁明了的三分钟小朋友自我介绍示例：\n\n大家好，我叫小明（或你的名字），今年6岁了，来自美丽的（城市名）。我是个快乐的小男孩。\n\n我喜欢画画，我的画笔下有彩虹和小动物，每次画画都让我感到非常开心。我也爱听故事，尤其是《安徒生童话》，它们带我进入一个奇妙的世界。我特别崇拜勇敢的消防员叔叔，他们总是第一时间帮助大家。\n\n在学校"},"finish_reason":"stop"}],"usage":{"prompt_tokens":27,"completion_tokens":**103**,"total_tokens":130}}

**Comment by juntao** [comment]
These answers seem to be cut off at the specific token length. Maybe the model itself does that? What is the context length for this model?

**Comment by njalan** [comment]
@juntao If I use the below command or webui then I can get the right answers except from the API.
wasmedge --dir .:. --nn-preload default:GGML:CPU:qwen1_5-7b-chat-q5_k_m.gguf llama-chat.wasm -c 2048 -n 512 -g 0 -p chatml .

**Comment by njalan** [comment]
@juntao I use new model chinese-llama-2-7b.Q5_K_S.gguf and got same result and "completion_tokens" is still 103

**Comment by njalan** [comment]
@juntao  I download the latest wasm llama-api-server.wasm and try with different model and all the completion_tokens is 103. Below is my command:
 curl -X POST http://xxxxx:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "how to learn  java"}]}'
{"id":"chatcmpl-62dd254d-259f-4312-ab73-598c27cc38b6","object":"chat.completion","created":1712026757,"model":"default","choices":[{"index":0,"message":{"role":"assistant","content":"1. 2008年6月3日，在google的blog上发表了一篇名为《java语言的未来》的文章。文章中提出了一个\"Java语言的未来\"的概念： Java语言将不再局限于运行于虚拟机之上，而是可以被编译成native code直接运行。"},"finish_reason":"stop"}],"usage":{"prompt_tokens":56,"completion_tokens":103,"total_tokens":159}}

I use below command the start api:
nohup wasmedge --dir .:. --nn-preload default:GGML:CPU:chinese-llama-2-7b.Q5_K_S.gguf llama-api-server.wasm -p chatml  --log-prompts > 1.log &

Anything wrong with my command?

**Comment by juntao** [comment]
The only thing I can think of is to change to a different system prompt.

**Comment by njalan** [comment]
What should I put for -p parameter?

**Comment by juntao** [comment]
The -p depends on how you trained your model. Did you use the llama2 chat template or chatml in training?

**Comment by njalan** [comment]
@juntao I just downloaded existing model and didn't do any training by myself.  I tried "role":"system", "content": "Answer as much as possible." and it is also return with "completion_tokens":103. But I found below error message in log:
"role":"system", "content": "Answer as much as possible."

**Comment by njalan** [comment]
@juntao  I tried to setup llama-api-server.wasm on one new server, After install plugin curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5 --plugins wasi_nn-ggml wasmedge_rustls
Then tried to start the api server got error message "**unknown option: nn-preload**" , I check there is no option nn-preload for new wasmedge, So how to load model by the latest wasmedge

**Comment by hydai** [comment]
What's the output of `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5 --plugins wasi_nn-ggml wasmedge_rustls`?

**Comment by njalan** [comment]
@hydai I fixed but in new server the completion_tokens is still 103.
 curl -X POST http://127.0.0.1:8080/v1/chat/completions   -H 'accept:application/json'   -H 'Content-Type: application/json'   -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "南京有什么好玩的"}]}'

{"id":"chatcmpl-63a005b6-3a46-4e70-9444-b1c003b812b6","object":"chat.completion","created":1712062640,"model":"default","choices":[{"index":0,"message":{"role":"assistant","content":"南京，作为中国历史文化名城和江苏省省会，拥有丰富的旅游资源。以下是一些推荐的游玩项目：\n\n1. **中山陵**：纪念孙中山先生的陵墓，风景优美，可了解其革命精神。\n2. **夫子庙秦淮河风光带**：古色古香的街巷，夜晚的秦淮灯会尤其有名。\n3. **南京博物院**：中国三大博物馆之一，藏品丰富，有深厚的历史底蕴。\n4. **"},"finish_reason":"stop"}],"usage":{"prompt_tokens":24,"completion_tokens":103,"total_tokens":127}}

**Comment by njalan** [comment]
@juntao Can you please give me one model and the full command for start llama-api-server.wasm in your local testing. Also the curl post command .  I want to use your command and model to test it locally. It is wired that I still get 103 completion_tokens by the post curl command.

**Comment by juntao** [comment]
The LlamaEdge one liner will install llama2 7b for you. You can access it via web ui or api. 

bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh')


https://llamaedge.com

**Comment by njalan** [comment]
@juntao I downloaded Llama-2-7b-chat-hf-Q5_K_M.gguf and here is my command to start the service: nohup wasmedge --dir .:. --nn-preload default:GGML:AUTO:Llama-2-7b-chat-hf-Q5_K_M.gguf llama-api-server.wasm --prompt-template llama-2-chat --model-name Llama-2-7b-chat-hf-Q5_K_M.gguf --socket-addr 0.0.0.0:8080 --log-prompts --log-stat > 1.log 
&

Here is my curl command:
curl -X POST http://localhost:8080/v1/chat/completions -H 'accept:application/json' -H 'Content-Type: application/json' -d '{"messages":[{"role":"system", "content": "Answer as concisely as possible."}, {"role":"user", "content": "南京有什么好玩的"}] }'
{"id":"chatcmpl-300ad33e-cbe7-4c2c-85c4-bf92b0467be4","object":"chat.completion","created":1712498259,"model":"Llama-2-7b-chat-hf-Q5_K_M.gguf","choices":[{"index":0,"message":{"role":"assistant","content":"Nanjing has many fun things to do! Here are a few recommendations:\n\n1. Visit the Purple Mountain (紫金山) - a popular hiking destination with beautiful scenery and historic sites.\n2. Explore the Nanjing City Wall (南京城墙) - a well-preserved ancient wall that offers great views of the city.\n3. Visit the Ming Xiaoling Mausoleum ("},"finish_reason":"stop"}],"usage":{"prompt_tokens":41,"**completion_tokens":103,**"total_tokens":144}}
completion_tokens is still 103 and only difference is that I am not able to add "model":"Llama-2-7b-chat-hf-Q5_K_M"} in the curl command since it will below error messages:
The model `Llama-2-7b-chat-hf-Q5_K_M` does not exist in the chat graphs

**Comment by juntao** [comment]
This is really strange. What is your hardware spec? I believe that you are using a CPU for inference? What is the exact CPU model and RAM size?

**Comment by njalan** [comment]
@juntao 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                208
On-line CPU(s) list:   0-207
Thread(s) per core:    2
Core(s) per socket:    26
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8270 CPU @ 2.70GHz
Stepping:              7
CPU MHz:               3399.884
CPU max MHz:           4000.0000
CPU min MHz:           1000.0000
BogoMIPS:              5400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76,80,84,88,92,96,100,104,108,112,116,120,124,128,132,136,140,144,148,152,156,160,164,168,172,176,180,184,188,192,196,200,204
NUMA node1 CPU(s):     1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,65,69,73,77,81,85,89,93,97,101,105,109,113,117,121,125,129,133,137,141,145,149,153,157,161,165,169,173,177,181,185,189,193,197,201,205
NUMA node2 CPU(s):     2,6,10,14,18,22,26,30,34,38,42,46,50,54,58,62,66,70,74,78,82,86,90,94,98,102,106,110,114,118,122,126,130,134,138,142,146,150,154,158,162,166,170,174,178,182,186,190,194,198,202,206
NUMA node3 CPU(s):     3,7,11,15,19,23,27,31,35,39,43,47,51,55,59,63,67,71,75,79,83,87,91,95,99,103,107,111,115,119,123,127,131,135,139,143,147,151,155,159,163,167,171,175,179,183,187,191,195,199,203,207
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
