### ISSUE TITLE
question: Using chat on Android device

### ISSUE THREAD

**Issue by akashicMarga** [LlamaEdge/LlamaEdge#144]
### Summary

I want to run chat application on my android device. So I have build wasmedge for Android using NDK and following below link:
https://wasmedge.org/docs/contribute/source/os/android/build

I have changed the build_for_android.sh to support ggml backend.

`#!/bin/bash

if [ ! $ANDROID_NDK_HOME ]; then
    echo "Environment variable ANDROID_NDK_HOME is not set."
    exit 1
else
    echo "Use Android NDK path: $ANDROID_NDK_HOME"
fi

WASMEDGE_ROOT_PATH=$(dirname $(dirname $(dirname $(dirname $0))))

cd ${WASMEDGE_ROOT_PATH}

if ! cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_USE_LLVM=OFF -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=23 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_ANDROID_STL_TYPE=c++_static -DWASMEDGE_BUILD_STATIC_LIB=ON -DWASMEDGE_LINK_TOOLS_STATIC=ON -DWASMEDGE_PLUGIN_WASI_NN_BACKEND=GGML -DWASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_BLAS=OFF; then
    echo === CMakeOutput.log ===
    cat build/CMakeFiles/CMakeOutput.log
    echo === CMakeError.log ===
    cat build/CMakeFiles/CMakeError.log
    exit 1
fi

cmake --build build

echo "Build finished."

# For the WASI-NN plugin, you should install this project.
cmake --install build

echo "install done.ß"
`

Build runs successfully. but while running in adb I am getting this error: 

command ->  1|violet:/data/local/tmp $ ./wasmedge/wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q5_K_M.gguf llama-chat.wasm --prompt-template llama>
error - > unknown option: nn-preload

![Screenshot 2024-04-08 at 4 13 27 PM](https://github.com/LlamaEdge/LlamaEdge/assets/18519731/b10d4bef-dbfc-44d6-a008-d90f9cec0765)

**Comment by juntao** [comment]
You will need to build the ggml plugin for Android as well. @hydai can you pint us to the instructions on how to compile the plugin from source? Thanks.

**Comment by alabulei1** [comment]
Hi  @singhaki 

You can check out this doc for building ggml/llama.cpp plugin from source. https://wasmedge.org/docs/contribute/source/plugin/wasi_nn#build-wasmedge-with-wasi-nn-llamacpp-backend

**Comment by singhaki** [comment]
> Hi  @singhaki 
> 
> 
> 
> You can check out this doc for building ggml/llama.cpp plugin from source. https://wasmedge.org/docs/contribute/source/plugin/wasi_nn#build-wasmedge-with-wasi-nn-llamacpp-backend
> 
> 

I tried general linux without acceleration from this doc. Can check the cmake build command i have attached in issue, if I missed anything.

**Comment by hydai** [comment]
@singhaki 
Do you set the plugin path?
https://wasmedge.org/docs/contribute/source/plugin/wasi_nn/#appendix

**Comment by singhaki** [comment]
Thanks @hydai  setting this param worked but when running in adb shell I am getting this error:

`Hello[2024-04-10 10:24:26.706] [error] [WASI-NN] GGML backend: Llama input is not set!
Error: "Operation error during the chat. Reason: Stream compute error. Backend Error: WASI-NN Backend Error: Caller module passed an invalid argument"`

using command:

`WASMEDGE_PLUGIN_PATH=/data/local/tmp/build/plugins/wasi_nn ./wasmedge/wasmedge --dir .:. --nn-preload default:GGML:AUTO:dolphin-2_6-phi-2-GGUF.gguf llama-chat.wasm --prompt-template phi-2-instruct
`

**Comment by hydai** [comment]
Please use options to log more information:

```
      --log-prompts
          Print prompt strings to stdout
      --log-stat
          Print statistics to stdout
      --log-all
          Print all log information to stdout
```

**Comment by singhaki** [comment]
Getting the same error not much info on error side.

![Screenshot 2024-04-13 at 9 17 36 PM](https://github.com/LlamaEdge/LlamaEdge/assets/18519731/6694cb27-fdf7-49ad-8894-0bc16a4208ff)
