### ISSUE TITLE
is there any plan to support  sqlcoder 

### ISSUE THREAD

**Issue by njalan** [LlamaEdge/LlamaEdge#147]
### Summary

In my testing it is not working with [sqlcoder-7b-2-GGUF](https://huggingface.co/MaziyarPanahi/sqlcoder-7b-2-GGUF)

**Comment by alabulei1** [comment]
Hi @njalan 

The  sqlcoder-7b-2 model isn't a chat model. You can use `llama-simple.wasm` to interact with this model.

I assumed you have installed WasmEdge and ggml plugin, downloadded the GGUF model. Next you run the following command line to download the `llama-simple.wasm` file.

```
curl -LO https://github.com/LlamaEdge/LlamaEdge/releases/latest/download/llama-simple.wasm
```
 
Then, run the following command line to run the model.

```
wasmedge --dir .:. --nn-preload default:GGML:AUTO:sqlcoder-7b-2.Q2_K.gguf  llama-simple.wasm \
  --prompt 'Generate a SQL query to select all users with age 18 and over '
```

Then, the output is as following:

```
[INFO] prompt context size: 4096
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 4096
[INFO] Log enable: false

[Answer]:


  SELECT u.user_id, u.user_name, u.user_first_name, u.user_last_name FROM users u WHERE EXTRACT(YEAR FROM AGE(u.user_date_of_birth)) >= 18;
```

Let me if this works for you. Thanks.

**Comment by njalan** [comment]
@alabulei1 Thanks for your reply.  It is working for llama-simple.wasm. How to run it with llama-api-server.wasm?
