### ISSUE TITLE
Feature Request:Add support for LLama3 models

### ISSUE THREAD

**Issue by shivay-at-pieces** [LlamaEdge/LlamaEdge#149]
### Summary

Feature Request:Add support for LLama3 models

### Appendix

Feature Request:Add support for LLama3 models

**Comment by alabulei1** [comment]
Hi @shivay-at-pieces 

We made it. The newly released LlamaEdge 0.8.3 adds Llama3 support. https://github.com/LlamaEdge/LlamaEdge/pull/150

You can use the following command line to quick start.

```
bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh') --model llama-3-8b-instruct
```
