### ISSUE TITLE
bug: Phi-3 will repeat the answer several times

### ISSUE THREAD

**Issue by alabulei1** [LlamaEdge/LlamaEdge#157]
### Summary

I used the following command to run the phi-3 model.

```
wasmedge --dir .:. --nn-preload default:GGML:AUTO:Phi-3-mini-4k-instruct-Q5_K_M.gguf llama-chat.wasm -p phi-3-chat -s "You are a friendly chatbot."
```

It answers other questions well. But when you say hi to the model, the model will repeat the answer several times.

```
[You]:
hello

[Bot]:
Hello there! How can I assist you today?
<|assistant|> Hi! It's great to see you. What brings you here today?
<|assistant|> Hey! Welcome back! Feel free to ask me anything or just chat if you like.
<|assistant|> Good day! I'm here to help with any questions or tasks you have in mind. How may I assist you?<|end|>
```

The version of llama-chat.wasm

```
wasmedge llama-chat.wasm -V
[2024-04-28 15:30:38.634] [error] instantiation failed: module name conflict, Code: 0x60
[2024-04-28 15:30:38.635] [error]     At AST node: module
llama-chat 0.8.5
```

Plugin version

```
[INFO] Plugin version: b2734 (commit d6e1d44f)
```

### Reproduction steps

See above

### Screenshots

![DESCRIPTION](LINK.png)

### Model Information

Phi-3-mini-4k-instruct-Q5_K_M.gguf

### Operating system information

mac 14.2.1

### ARCH

arm 64

### CPU Information

Apple M2

### Memory Size

16 GB

### GPU Information

Apple M2

### VRAM Size

none

**Comment by hydai** [comment]
Please try again with the latest version. There is a bugfix for phi-3.

**Comment by apepkuss** [comment]
@alabulei1 The issue is still there on your side? Thanks.

**Comment by alabulei1** [comment]
It solved. Thanks.

<img width="1463" alt="image" src="https://github.com/LlamaEdge/LlamaEdge/assets/45785633/8e5c0a84-616f-4f3d-bbce-57b59ceabc8b">
