### ISSUE TITLE
bug: Segmentation fault (core dumped) when requesting embeddings

### ISSUE THREAD

**Issue by vinhdq844** [LlamaEdge/LlamaEdge#163]
### Summary

I ran an API server and sent a request, but received an empty reply and the server was down.

Input:
```bash
curl -X POST http://localhost:2001/v1/embeddings \
    -H 'accept:application/json' \
    -H 'Content-Type: application/json' \
    -d '{"model": "e5-mistral-7b-instruct", "input":["Paris, city and capital of France, ... and far beyond both banks of the Seine.","Paris occupies a central position in the rich agricultural region ... metropolitan area, 890 square miles (2,300 square km).","Pop. (2020 est.) city, 2,145,906; (2020 est.) urban agglomeration, 10,858,874.","For centuries Paris has been one of the world’s ..., for Paris has retained its importance as a centre for education and intellectual pursuits.","Paris’s site at a crossroads of both water and land routes ... The Frankish king Clovis I had taken Paris from the Gauls by 494 CE and later made his capital there.","Under Hugh Capet (ruled 987–996) and the Capetian dynasty ..., drawing to itself much of the talent and vitality of the provinces."]}'
```
Output:
```bash
curl: (52) Empty reply from server
```

Additionally, I want to ask which type of pooling method the embeddings endpoint uses. I noticed that `intfloat/e5-mistral-7b-instruct` uses last `</s>` token pooling, while `nomic-ai/nomic-embed-text-v1.5` and `sentence-transformers/all-MiniLM-L6-v2` use mean pooling. I am wondering how you handle these.

## Install WasmEdge
```bash
# install libopenblas-dev
apt update && apt install -y libopenblas-dev

# install WasmEdge with wasi-nn-ggml plugin
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml

# Assuming you use bash (the default shell on Ubuntu), run the following command to activate the environment
source $HOME/.bashrc
```

## Downloads
```bash
curl -L https://huggingface.co/second-state/E5-Mistral-7B-Instruct-Embedding-GGUF/resolve/main/e5-mistral-7b-instruct-Q5_K_M.gguf --output e5-mistral-7b-instruct-Q5_K_M.gguf
```

```bash
curl -LO https://github.com/LlamaEdge/LlamaEdge/releases/latest/download/llama-api-server.wasm
```

## Run
```bash
wasmedge --dir .:. --nn-preload default:GGML:AUTO:e5-mistral-7b-instruct-Q5_K_M.gguf   llama-api-server.wasm   --prompt-template llama-2-chat   --ctx-size 4096   --model-name e5-mistral-7b-instruct --socket-addr 0.0.0.0:2001
```

### Any logs you want to share for showing the specific issue

[INFO] LlamaEdge version: 0.10.0
[INFO] Model name: e5-mistral-7b-instruct
[INFO] Model alias: default
[INFO] Context size: 4096
[INFO] Prompt template: llama-2-chat
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 1
[INFO] Top-p sampling (1.0 = disabled): 1
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Presence penalty (0.0 = disabled): 0
[INFO] Frequency penalty (0.0 = disabled): 0
[INFO] Enable prompt log: false
[INFO] Enable plugin log: false
[INFO] Socket address: 0.0.0.0:2001
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
[INFO] Wasi-nn-ggml plugin: b2781 (commit 6ecf3189)
[INFO] LlamaEdge API server listening on http://0.0.0.0:2001

[+] Running embeddings handler ...
Segmentation fault (core dumped)

### Model Information

e5-mistral-7b-instruct-Q5_K_M.gguf

### Operating system information

Ubuntu 22.04.3 LTS

### ARCH

x86_64

### CPU Information

 Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz

### Memory Size

64GB

### GPU Information

2x NVIDIA GeForce RTX 4090

### VRAM Size

2x 24GB

**Comment by juntao** [comment]
There seems to be an issue between this GGUF conversion and the latest llama.cpp build. We will look into it. 

In the meanwhile, the nomic embedding model should work.

**Comment by vinhdq844** [comment]
> @vinhdq844 The issue is still there on your side? Thanks.

@apepkuss Hi, I tried the above reproduction steps on a new machine and this occurred. Thanks.
![image](https://github.com/LlamaEdge/LlamaEdge/assets/169571205/02fc86c8-4b61-4127-9767-4b7dc4dd8a99)

**Comment by hydai** [comment]
Hi @vinhdq844 
We introduced a new logging system to retrieve more debug information, so it requires more plugins. Please use the following command to install and try again:

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s -- -v 0.13.5
```

**Comment by vinhdq844** [comment]
> Hi @vinhdq844 We introduced a new logging system to retrieve more debug information, so it requires more plugins. Please use the following command to install and try again:
> 
> ```
> curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s -- -v 0.13.5
> ```

I can start the server now. But:
- when resquesting for embedding: received error response `500 Internal Server Error: Computing embeddings is not supported in the chat mode.` and server error log (How can I switch out chat mode?)
![image](https://github.com/LlamaEdge/LlamaEdge/assets/169571205/5dda6e60-f9ce-4988-8292-30a86b587269)

-  when requesting for model list:
![image](https://github.com/LlamaEdge/LlamaEdge/assets/169571205/d3181c5a-c808-455b-b539-843c5c744ae5)

Thanks.

**Comment by apepkuss** [comment]
@vinhdq844 If you used `wasmedge --dir .:. --nn-preload default:GGML:AUTO:e5-mistral-7b-instruct-Q5_K_M.gguf   llama-api-server.wasm   --prompt-template llama-2-chat   --ctx-size 4096   --model-name e5-mistral-7b-instruct --socket-addr 0.0.0.0:2001` to start the api server, please update `--prompt-template llama-2-chat` to `--prompt-template embedding`.

**Comment by vinhdq844** [comment]
> @vinhdq844 If you used `wasmedge --dir .:. --nn-preload default:GGML:AUTO:e5-mistral-7b-instruct-Q5_K_M.gguf llama-api-server.wasm --prompt-template llama-2-chat --ctx-size 4096 --model-name e5-mistral-7b-instruct --socket-addr 0.0.0.0:2001` to start the api server, please update `--prompt-template llama-2-chat` to `--prompt-template embedding`.

it said `500 Internal Server Error: The model `e5-mistral-7b-instruct-Q5_K_M` does not exist in the embedding graphs.`
![image](https://github.com/LlamaEdge/LlamaEdge/assets/169571205/e4bc8e02-4c2d-4337-90cd-47ccfafb8322)

**Comment by apepkuss** [comment]
@vinhdq844 Please share with us both the command of starting the api-server and the request you sent to the server. Thanks!

**Comment by vinhdq844** [comment]
@apepkuss Oh sorry, I used an incorrect model name last time. I can confirm that the issue still persists on my side:
- Start the api-server
```bash
wasmedge --dir .:. --nn-preload default:GGML:AUTO:e5-mistral-7b-instruct-Q5_K_M.gguf   llama-api-server.wasm   --prompt-template embedding   --ctx-size 4096   --model-name e5-mistral-7b-instruct --socket-addr 0.0.0.0:2001
```

- Request
```bash
curl -X POST http://localhost:2001/v1/embeddings \
    -H 'accept:application/json' \
    -H 'Content-Type: application/json' \
    -d '{"model": "e5-mistral-7b-instruct", "input":["Paris, city and capital of France, ... and far beyond both banks of the Seine.","Paris occupies a central position in the rich agricultural region ... metropolitan area, 890 square miles (2,300 square km).","Pop. (2020 est.) city, 2,145,906; (2020 est.) urban agglomeration, 10,858,874.","For centuries Paris has been one of the world’s ..., for Paris has retained its importance as a centre for education and intellectual pursuits.","Paris’s site at a crossroads of both water and land routes ... The Frankish king Clovis I had taken Paris from the Gauls by 494 CE and later made his capital there.","Under Hugh Capet (ruled 987–996) and the Capetian dynasty ..., drawing to itself much of the talent and vitality of the provinces."]}'
```

![image](https://github.com/LlamaEdge/LlamaEdge/assets/169571205/355f1857-a945-4d3a-894e-f74426d0a3fd)

Thanks.

**Comment by apepkuss** [comment]
@hydai Could you please help check the issue? A segment fault happened during the computation. Thanks!

**Comment by hydai** [comment]
The ggml plugin version is too old (b2781). Please update the plugin and try again.
