### ISSUE TITLE
question: Is windows (without WSL) supported?

### ISSUE THREAD

**Issue by aeroaks** [LlamaEdge/LlamaEdge#165]
### Summary

I do not have access to WSL and I am using Windows. Can I use (with or without building) Llamaedge on Windows?

**Comment by alabulei1** [comment]
Hi @aeroaks 

We now don't support Windows OS. However, the windows OS support is on the way. Will let you know when it's ready. Thanks

**Comment by aeroaks** [comment]
Thanks. Will try to keep an eye for it.

**Comment by apepkuss** [comment]
Closed. Please re-open it if any further question. Thanks!
