### ISSUE TITLE
bug: "Might an invalid wasm file"

### ISSUE THREAD

**Issue by HyperCrowd** [LlamaEdge/LlamaEdge#180]
### Summary

On Ubuntu 20.04 LTS, `llama-simple.wasm` doesn't work.  I get the following errors running `wasmedge llama-simple.wasm`:

```
[2024-06-06 20:41:17.036] [error] Might an invalid wasm file
[2024-06-06 20:41:17.036] [error] loading failed: magic header not detected, Code: 0x103
[2024-06-06 20:41:17.036] [error]     Bytecode offset: 0x00000000
[2024-06-06 20:41:17.036] [error]     At AST node: component
[2024-06-06 20:41:17.036] [error]     File name: "llama-simple.wasm"
```

### Reproduction steps

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
curl -LO https://github.com/LlamaEdge/LlmaEdge/releases/latest/download/llama-simple.wasm
wasmedge llama-simple.wasm
```

### Screenshots

![DESCRIPTION](LINK.png)

### Model Information

The model doesn't matter.  This error happens with or without models

### Operating system information

Ubuntu 20.04 LTS

### ARCH

x86_64

### CPU Information

AMD Ryzen 7 5700U with Radeon Graphics

### Memory Size

32GB

### GPU Information

05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 164c (rev c1)

### VRAM Size

very low, I don't have a GPU

**Comment by hydai** [comment]
@HyperCrowd 
How do you get this wasm file?
Could you please print the output of `cat llama-simple.wasm`?

**Comment by HyperCrowd** [comment]
Woah, the output is `Not found`

The command is `curl -LO https://github.com/LlamaEdge/LlmaEdge/releases/latest/download/llama-simple.wasm`

I guess that's the wrong path?

**Comment by HyperCrowd** [comment]
Got the right URL -_-'

Thanks for the speedy response!
