### ISSUE TITLE
question: cuda-11 is not supported.

### ISSUE THREAD

**Issue by shkr** [LlamaEdge/LlamaEdge#19]
### Summary

When starting rest api server on an ubuntu cuda 12.2 I am running into an error

Please help

### Reproduction steps

bash <(curl -sSf https://raw.githubusercontent.com/second-state/llama-utils/main/run-llm.sh);

chose rest api server

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

```
+ wasmedge --dir .:. --nn-preload default:GGML:AUTO:openhermes-2.5-mistral-7b.Q5_K_M.gguf llama-api-server.wasm -p chatml -r '<|im_end|>'
[2023-12-05 23:08:10.452] [error] loading failed: invalid path, Code: 0x20
[2023-12-05 23:08:10.452] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
[2023-12-05 23:08:10.453] [error] loading failed: invalid path, Code: 0x20
[2023-12-05 23:08:10.453] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
unknown option: nn-preload
+ set +x
```

### Model Information

openhermes-2.5-mistral-7b.Q5_K_M.gguf

### Operating system information

Ubuntu 22.04

### ARCH

x86_64

### CPU Information

Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz

### Memory Size

108GB

### GPU Information

NVIDIA L4

### VRAM Size

24

**Comment by hydai** [comment]
Hi @shkr 
Could you please check if the `libcudart.so.12` is installed on your environment?

If the default search path is not working, you may need to setup the `LD_LIBRARY_PATH` with the installed path:

```bash
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
```

FYR, in our AWS machine A10G instance, the library path is under the following folder:

```
libcudart.so.12 => /usr/local/cuda/lib64/libcudart.so.12 (0x00007f6b7b600000)
```

**Comment by shkr** [comment]
I ran 

```
find / -name 'libcudart.so'
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
```

```
➜  ~ ls /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart*
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so       /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so.11.8.89
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so.11.0  /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart_static.a
➜  ~ 
```



I can find libcudart.so.11.0 but not libcudart.so.12

**Comment by shkr** [comment]
I ran the wasmedge runtime after adding libcudart.so to the LD_LIBRARY_PATH

```
➜  ~ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda-11.8/targets/x86_64-linux/lib/:/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so:/usr/local/cuda/lib64:/usr/local/cuda-11.8/targets/x86_64-linux/lib/:/usr/local/cuda/lib64:/root/.wasmedge/lib
➜  ~ wasmedge --dir .:. --nn-preload default:GGML:AUTO:zephyr-7b-alpha.Q5_K_M.gguf llama-api-server.wasm -p llama-2-chat
[2023-12-06 08:52:24.752] [error] loading failed: invalid path, Code: 0x20
[2023-12-06 08:52:24.752] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
[2023-12-06 08:52:24.752] [error] loading failed: invalid path, Code: 0x20
[2023-12-06 08:52:24.752] [error]     load library failed:libcudart.so.12: cannot open shared object file: No such file or directory
unknown option: nn-preload
➜  ~ 
```

Same issue

**Comment by hydai** [comment]
Hi @shkr 
Please install cuda-12. Our prebuilt binary is using cuda-12.

**Comment by shkr** [comment]
Can you share instructions with best way to install cuda 12 given cuda 11.8 is already installed. I don't want to mess up the machine

**Comment by hydai** [comment]
Please follow the guide provided by NVIDIA: https://developer.nvidia.com/cuda-downloads

It will install cuda 12 in `/usr/local/cuda-12`. Then you can run the following commands before running wasmedge:

```
export PATH="/usr/local/cuda-12/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-12/lib64:$LD_LIBRARY_PATH"
```
