### ISSUE TITLE
How to run CPUONLY?

### ISSUE THREAD

**Issue by 0wwafa** [LlamaEdge/LlamaEdge#192]
### Summary

How to run it without cuda/gpu?

**Comment by hydai** [comment]
You can set the following option to control it:

```
  -g, --n-gpu-layers <N_GPU_LAYERS>
          Number of layers to run on the GPU [default: 100]
```

`0` will not offload any layers to the GPU.

**Comment by 0wwafa** [comment]
thanks.. I missed it.. sometime I have what I call "selective blindness" :D 
anyway, I see that llamaedge uses llama.cpp in wasm and I think that's a big overhead.
llama.cpp + chat-ui is way faster.

**Comment by juntao** [comment]
It is actually not slower than llama.cpp. It is almost the same number of tokens per second across hardware platforms. 😂

**Comment by apepkuss** [comment]
Closed. Please re-open it if any further question. Thanks!
