### ISSUE TITLE
bug: WasmEdge error when running llama-api-server with the "full" or "https" llama-core feature

### ISSUE THREAD

**Issue by suryyyansh** [LlamaEdge/LlamaEdge#200]
### Summary

The server fails to run when compiled with the "full" or "https" feature for the llama-core crate, failing with the following error log:
```
[2024-07-30 18:58:09.248] [error] instantiation failed: unknown import, Code: 0x302
[2024-07-30 18:58:09.248] [error]     When linking module: "rustls_client" , function name: "new_codec"
[2024-07-30 18:58:09.248] [error]     At AST node: import description
[2024-07-30 18:58:09.248] [error]     At AST node: import section
[2024-07-30 18:58:09.248] [error]     At AST node: module
```

### Reproduction steps

1. compile the llama-api-server with `$ cargo build -r --target wasm32-wasip1 --features full` (also happens when compiling to the older `wasm32-wasi`)
2. run the llama api server. (`$ wasmedge llama-api-server.wasm`)
3. encounter error.

### Any logs you want to share for showing the specific issue

```
$ wasmedge --version
wasmedge version 0.14.0
/home/nsen/.wasmedge/lib/../plugin/libwasmedgePluginWasiLogging.so (plugin "wasi_logging") version 0.1.0.0
/home/nsen/.wasmedge/lib/../plugin/libwasmedgePluginWasiNN.so (plugin "wasi_nn") version 0.10.1.0
```

WasmEdge installation (it wasn't detecting CUDA or logging things properly with the `install.sh` script):
```
$ curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh | bash -s -- -c12 -v 0.14.0
```

### Model Information

N/A

### Operating system information

Ubuntu 24.04 Linux 6.8.0-39-generic

### ARCH

x86_64

### CPU Information

12th Gen Intel® Core™ i5-12450H

### Memory Size

16GB

### GPU Information

NVIDIA RTX 4060 Max-Q

### VRAM Size

8GB

**Comment by juntao** [comment]
I believe the full api server requires the rustls plugin to run. But that plugin is only available for 0.13.5 and not for 0.14.

You will need to install WasmEdge 0.13.5 and download the plugin-wasmedge-rustls for your platform.  You will put the downloaded .so file into you WasmEdge's lib directory. 

https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.5

**Comment by suryyyansh** [comment]
This fixed it, with
```bash
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml-cuda wasi_logging wasmedge_rustls -v 0.13.5
```
but the docs mention [here](https://wasmedge.org/docs/start/install#tls-plug-in) that v0.14.0 comes with TLS capabilities built in

**Comment by juntao** [comment]
Yes, for 0.14.0, we require code change in the application (breaks compatibility) to use HTTPS. We have not update the `full` API server to 0.14 API yet.
