### ISSUE TITLE
question: What's the logic of exclusively using the wasmedge frontend?

### ISSUE THREAD

**Issue by shakfu** [LlamaEdge/LlamaEdge#214]
### Summary

I have an inkling that the greatest benefit is portability. But are there any other reasons? Is there a way to build llamaedge applications 'without' wasmedge, i.e. as a regular rust executable? or to combine a model with the inference engine part to have a single runnable model?

**Comment by shakfu** [comment]
Ok [this page](https://www.secondstate.io/articles/fast-llm-inference/) is relevant to answer part of my question:

> Compared with Python, Rust+Wasm apps could be 1/100 of the size, 100x the speed, and most importantly securely run everywhere at full hardware acceleration without any change to the binary code. [Rust is the language of AGI](https://blog.stackademic.com/why-did-elon-musk-say-that-rust-is-the-language-of-agi-eb36303ce341).

> We created a very simple [Rust program](https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/wasmedge-ggml-llama-interactive) to run inference on llama2 models at native speed. When compiled to Wasm, the [binary application](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml-llama-interactive/wasmedge-ggml-llama-interactive.wasm) (only 2MB) is completely portable across devices with heterogeneous hardware accelerators. The Wasm runtime ([WasmEdge](https://github.com/WasmEdge/WasmEdge)) also provides a safe and secure execution environment for cloud environments. In fact, the [WasmEdge runtime works seamlessly with container tools](https://wasmedge.org/docs/start/build-and-run/docker_wasm) to orchestrate and execute the portable application across many different devices.

**Comment by shakfu** [comment]
@juntao Yes, I get that.  But is there still an option to compile a non-wasm based executable?

**Comment by juntao** [comment]
You sure can. But then you can also compile llama.cpp for different platforms by hand. ;)

LlamaEdge compiles to the WASI NN API and then the runtime figures out how to translate WASI NN calls to the underlying framework calls. I guess you can create a WASI NN compatible FFI bridge. That would allow LlamaEdge programs to compile to native.

**Comment by shakfu** [comment]
Thanks @juntao 

That's great.. I have already compiled `llama.cpp` and I'm using it as my main inference engine, but I'm interested in rust inference engines so it'd be good to understand llamaedge's rust stack more and also candle's.
