### ISSUE TITLE
question: api key

### ISSUE THREAD

**Issue by michelgirault** [LlamaEdge/LlamaEdge#247]
### Summary

is there a way to set an api key on the llama edge server? i could not find this information in the document like you have on llamacpp server : --api-key

**Comment by apepkuss** [comment]
Thanks for the question. Is the API key for allowing users to access LlamaEdge itself
?

**Comment by michelgirault** [comment]
the api key in order for user or service to submit to the openai api

**Comment by apepkuss** [comment]
Like the request with api-key, right?

```bash
curl --location 'http://localhost:8080/v1/chat/completions' \
--header 'Authorization: Bearer $API_KEY' \
--header 'Content-Type: application/json' \
--data '...'
```

**Comment by michelgirault** [comment]
yes thats correct

**Comment by alabulei1** [comment]
Hi  @michelgirault 

We have supported the API key. Please give it a try and let me know if it works for you. Thanks.

**Comment by michelgirault** [comment]
works well thanks a lot
