### ISSUE TITLE
question: Support embedding?

### ISSUE THREAD

**Issue by katopz** [LlamaEdge/LlamaEdge#56]
### Summary

refer to https://github.com/second-state/llama-utils/blob/008da32d648ce4bab40fd029a55a3f72068600cf/api-server/llama-api-server/src/backend/mod.rs#L21

I can see embeddings has been comment out, not sure what need to be done here?

Thanks

**Comment by alabulei1** [comment]
@apepkuss Can you please take a look at this issue?

**Comment by katopz** [comment]
FYI: I aim to target `bert`, `distrill-bert`, `jina-bert`, maybe we can get an idea from candle  

- [bert](https://github.com/huggingface/candle/blob/1fb2dd9/candle-examples/examples/bert/main.rs)
- [distrill-bert](https://github.com/huggingface/candle/blob/1fb2dd9/candle-examples/examples/distilbert/main.rs)
- [jina-bert](https://github.com/huggingface/candle/blob/1fb2dd905cb49ce99b7a7c31f5d0809382bc12f3/candle-examples/examples/jina-bert/main.rs)

**Comment by apepkuss** [comment]
@katopz The idea is great! We'll add it to the task list, but we cannot guarantee the schedule, as we do not have enough hands to do it now. Thanks a lot!

**Comment by katopz** [comment]
Thanks, I think [fastembed-rs](https://github.com/Anush008/fastembed-rs) is a good start for target `Wasm`, I will give it a try on my free time.

**Comment by hydai** [comment]
The embedding mode is supported. Please try the latest version.
