### ISSUE TITLE
feat: Support for OpenAI Function Calling (for full drop-in replacement)

### ISSUE THREAD

**Issue by ChristianWeyer** [LlamaEdge/LlamaEdge#72]
### Summary

Hello all!

**Problem**
AFAICS, the current implementation does not have OpenAI Function Calling support. This would be a fantastic, powerful, and much needed feature. Almost any serious LLM integration application needs OAI Function Calling support - so we do as well for Open Source LLMs.

**Success Criteria**
Any OAI client can be used with LlamaEdge via the API server, even (and especially) those that use OAI Function Calling.

Reference:
https://platform.openai.com/docs/guides/function-calling
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

Thank you!

**Comment by juntao** [comment]
Yes, this is much needed. But it also heavily depends on the model. The model must be fine-tuned in a way that it generates reliable JSON responses. We will be looking for these.

**Comment by ChristianWeyer** [comment]
Just wanted to check where we are with this?
With the upcoming wave of agent-based systems, Function Calling / Tools will be a very essential feature for successfully implementing agents on the edge.

**Comment by ChristianWeyer** [comment]
> Yes, this is much needed. But it also heavily depends on the model. The model must be fine-tuned in a way that it generates reliable JSON responses. We will be looking for these.

Just wanted to check where we are with this?
With the upcoming wave of agent-based systems, Function Calling / Tools will be a very essential feature for successfully implementing agents on the edge.

**Comment by ChristianWeyer** [comment]
Do you guys have any prio for this?

Supporting Open AI Tools calling (aka Function calling) would be killer! This would enable 'micro agents' running on edge devices being access programmatically in a standardized way.

.cc @juntao

**Comment by juntao** [comment]
Hi @ChristianWeyer 

Yes, we have several things going on here. First, check out our support for the Command-R model, which is ranked pretty high in function calling benchmarks.

https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/wasmedge-ggml/command-r

Then, this pending PR showcases how to force-generate JSON text that is suitable for function calling.

https://github.com/second-state/WasmEdge-WASINN-examples/pull/127/files

After it is merged, we will be adding some actual function calling endpoints to the LlamaEdge API server, and then provide developers a way to add their own endpoints.

Please help us test / plan these features. :)

**Comment by ChristianWeyer** [comment]
Nice, looking forward to those!
Thanks for the hard work.

Full Open AI API compat will be a real milestone.

**Comment by ChristianWeyer** [comment]
Hey @juntao - just checking in and bumping... 😅.

Do you already know when Function / Tool Calling will make it into awesome-llamaedge?

**Comment by apepkuss** [comment]
@ChristianWeyer We introduced support for the `tool use` feature in [LlamaEdge v0.12.2](https://github.com/LlamaEdge/LlamaEdge/releases/tag/0.12.2). For now, we verified the support with two popular models: [Mistral-7B-Instruct-v0.3-GGUF](https://huggingface.co/second-state/Mistral-7B-Instruct-v0.3-GGUF) and [Hermes-2-Pro-Llama-3-8B-GGUF](https://huggingface.co/second-state/Hermes-2-Pro-Llama-3-8B-GGUF). They work well. If you still have interests in the `tool use` feature, you can try it by following the steps in [TooUse.md](https://github.com/LlamaEdge/LlamaEdge/blob/main/api-server/ToolUse.md). Thanks!

**Comment by ChristianWeyer** [comment]
Great, thank you!
