### ISSUE TITLE
Feature Request: Android support

### ISSUE THREAD

**Issue by niutech** [LlamaEdge/LlamaEdge#95]
### Summary

WasmEdge [supports Android](https://wasmedge.org/docs/category/build-and-run-wasmedge-on-android) so is it possible for LlamaEdge to run in Android, using GPU or CPU for inference?

### Appendix

The goal is to use an offline LLM (~3B) on the tablet.

**Comment by juntao** [comment]
I believe we do. You just need to use the Android NDK to recompile the plugin. Would you mind trying it? Thanks.
